export enum COL_POSITION {
  COL_A = 1,
  COL_B = 2,
  COL_C = 3,
  COL_D = 4,
  COL_E = 5,
  COL_F = 6,
  COL_G = 7,
}

export enum COL_LOTO_CHAR_POSTION {
  COL_I = 'I',
  COL_J = 'J',
  COL_K = 'K',
  COL_L = 'L',
  COL_M = 'M',
  COL_N = 'N',
  COL_O = 'O',
  COL_P = 'P',
  COL_Q = 'Q',
  COL_R = 'R',
  COL_S = 'S',
  COL_T = 'T',
  COL_U = 'U',
  COL_V = 'V',
  COL_W = 'W',
  COL_X = 'X',
  COL_Y = 'Y',
  COL_Z = 'Z',
  COL_AA = 'AA',
  COL_AB = 'AB',
  COL_AC = 'AC',
  COL_AD = 'AD',
  COL_AE = 'AE',
  COL_AF = 'AF',
  COL_AG = 'AG',
  COL_AH = 'AH',
  COL_AI = 'AI',
  COL_AJ = 'AJ',
  COL_AK = 'AK',
  COL_AL = 'AL',
  COL_AM = 'AM',
}
